// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameModel3dAsset = { path: string, sha256: string, bytes: bigint, rigKind: string, animationClips: Array<string>, };
