// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type GameGeneration = { id: string, projectId: string, targetKind: string, targetRef: string, stage: string, variant: string | null, filePath: string, fileHash: string | null, isFinal: boolean, source: string, taskId: string | null, assetSpec: JsonValue, createdAt: bigint, };
