// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAiUsageBudget = { limitKind: string, used: bigint, limit: bigint, periodExpr: string, windowKey: string, groupName: string, source: string, exhausted: boolean, unlimited: boolean, };
