// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAiLimit } from "./GameAiLimit";

export type GameAiModel = { id: string, providerCode: string, modelId: string, displayName: string, capabilities: Array<string>, driver: string, apiPath: string, enabled: boolean, sortNo: bigint, paramsJson: string, remark: string, limits: Array<GameAiLimit>, };
