// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameArtifactDraft = { id: string, conversationId: string, targetPath: string, content: string, basedOnHash: string | null, status: string, createdAt: bigint, };
