// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameCharacterWorkflowStep } from "./GameCharacterWorkflowStep";

export type GameCharacterWorkflowProgress = { statusLabel: string, steps: Array<GameCharacterWorkflowStep>, needsResume: boolean, continuationKey: string | null, };
