// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameModel3dAsset } from "./GameModel3dAsset";

export type GameModel3dJob = { id: string, projectId: string, characterId: string, providerCode: string, status: string, stage: string, rigKind: string | null, asset: GameModel3dAsset | null, error: string | null, createdAt: bigint, updatedAt: bigint, };
