// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAgentHandoff = { id: bigint, conversationId: string, turn: bigint, fromAgentCode: string, toAgentCode: string, source: string, reason: string, status: string, createdAt: bigint, };
