// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAiAgent = { agentCode: string, role: string, capability: string, outputContract: string, sourceFile: string, modelIds: Array<string>, };
