// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAiAgent = { agentCode: string, role: string, roleType: string, capability: string, requiredModelCapability: string, focusable: boolean, aliases: Array<string>, targetKinds: Array<string>, stages: Array<string>, maxTurns: number, conversational: boolean, memoryScope: string, contextBudget: number, maxOutputTokens: number | null, outputContract: string, allowTools: Array<string>, sourceFile: string, modelIds: Array<string>, };
