// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAiBreaker } from "./GameAiBreaker";
import type { GameAiUsageBudget } from "./GameAiUsageBudget";

export type GameAiModelUsage = { providerCode: string, providerName: string, providerModelId: string, modelId: string, providerEnabled: boolean, enabled: boolean, hasKey: boolean, agents: Array<string>, budgets: Array<GameAiUsageBudget>, breaker: GameAiBreaker | null, };
