// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type GameCharacter = { id: string, projectId: string, name: string, group: string | null, dirName: string, state: string, specPath: string | null, renderPath: string | null, viewPaths: JsonValue, hardConstraints: Array<JsonValue>, gateSpecConfirmedAt: bigint | null, gateRenderConfirmedAt: bigint | null, gateViewsConfirmedAt: bigint | null, createdAt: bigint, updatedAt: bigint, };
