// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameAiLimit } from "./GameAiLimit";

export type GameModelRecommendation = { providerCode: string, providerName: string, driver: string, defaultBaseUrl: string, modelId: string, displayName: string, capabilities: Array<string>, recommended: boolean, defaultLimits: Array<GameAiLimit>, };
