// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

export type GameMessage = { id: string, turn: bigint, role: string, content: string, agentCode: string, recipientAgentCode: string | null, status: string, tokenCount: bigint, folded: boolean, attachments: Array<JsonValue>, action: JsonValue | null, createdAt: bigint, };
