// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameProviderPresetModel } from "./GameProviderPresetModel";

export type GameProviderPreset = { code: string, vendor: string, plan: string, label: string, baseUrl: string, driver: string, authStyle: string, keyPrefix: string | null, models: Array<GameProviderPresetModel>, };
